### ISSUE TITLE
the deployment grind | Heroku / full hand made / Docker

### ISSUE THREAD

**Issue by linmiao** [linmiao/linmiao.github.io#3]
这两天试着自己部署点东西，想找个不太费心的办法，第一个就选了Heroku。

### Heroku
Heroku 确实很好用，方便快捷。        
操作步骤的话，这篇已经解释得很好了，请移步 [nodejs包教不包会](https://github.com/alsotang/node-lessons/tree/master/lesson12)     
这里简单总结一下，如果想用 Heroku 部署node+postgresql项目，注册好Heroku账号以后，要做的仅仅两步：       
1. 把项目代码推给Heroku，Heroku检测出node代码，线上环境自动给搭好。
2. 添加一个 postgresql addon，得到一个 postgresql 服务配置，配置好了以后，biu，上线。
用Heroku部署，听起来非常简单轻松，它的addon库也很强大很好用。   
  
⚠️ Heroku 部署时有一个小坑，在没有指定process.env.port的情况下，端口要写成 process.env.port | 3000，写成3000以外的端口，会报H10这个错       

但是，Heroku是依靠AWS建立的，那么，很有可能，你的项目一出生就在墙的另一头......      
再见。      

### 全手动
全自动的用起来受挫了，那就全手动一下吧。弄了个阿里云账号，按照官网说的一步步装node，再装postgresql，系统是centos 7+             
但问题来了，npm有个包怎么也装不上，左调右调持续报错。报错到心情沉郁          
想说，有没有办法能把环境打包带走，开发和线上环境一个样呢？Docker

### Docker
想看视频的话，请移步 Ben Awad 的 [Docker Compose Node.js, Redis, and PostgreSQL](https://www.youtube.com/watch?v=aetqo2nkQcA)   
> 部署Docker前，请先注册好自己的云服务器账号密码，再把项目源码推到线上，接下来提到的**运行命令**都是在线上进行的 
      
简单来说Docker部署 node+postgresql 也是两步，不过不能像 Heroku 那样推个代码搞定一切，部署 Docker 项目还是要用点心的：
#### 1. 制作项目源码 node 镜像（写一个Dockerfile文件）
```
FROM node:carbon

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .
COPY wait-for-it.sh .

EXPOSE 3000

CMD ["npm", "start"]
```
这一步要做的事情有这么几个 ：
> 指定node环境镜像、镜像存放地址、node_modules安装文件和办法、要复制的项目源码、对外端口、运行镜像时执行的命令

在线上运行docker镜像和容器（⚠️ 制作镜像时app名旁边还有个点儿 . 漏了就会运行失败）
```
sudo docker build -t app_name .
docker run -d -p port_for_you:port_for_outsider app_name
```
#### 2. 从官网 pull 一个 postgresql 镜像
```
docker pull postgres
```
#### 3. 关联node和postgresql镜像（写一个docker-compose.yml文件） 
这步也很简单：
> 定义docker-compose版本、postgresql配置、node项目配置   
    
⚠️ 这里有两个潜的坑：
a. 端口一定要指明，否则外部无法访问      
b. node项目可能在服务器运行之前先跑起来了，这样会导致服务器连接失败      
可以使用wait-for-it.sh的设置，让node项目先等等服务器        
```
version: "3"
services:
  db:
    image: postgres
    ports:
          - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pswd
      POSTGRES_USER: user_name
      POSTGRES_DB: db_name
      DATABASE_URL: postgres://user_name:pswd@host:port/db_name
  web:
    image: node-app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      POSTGRES_DB: db_name
      POSTGRES_USER: user_name
      POSTGRES_PASSWORD: pswd
      POSTGRES_HOST: db
    command: ["./wait-for-it.sh", "db:5432", "--", "npm", "start"]
```
#### 4. 运行 docker-compose
镜像都有了，现在该让 Docker 集装箱跑起来了🐒！
```
docker-compose up
```
#### 最后，一点点给小白的彩蛋
1. 旧的docker-compose项目停不下来，占了port，导致新的无法启动怎么办
```
docker-compose down
docker rm -fv $(docker ps -aq)
sudo lsof -i -P -n | grep 5432
kill -9 <process id>
```
2. docker容器中怎么进入数据库
```
docker exec -it db /bin/bash
psql -U postgres
```
3. docker postgres 容器里的数据不持续怎么办  
docker-compose.yml 的db配置里加一条volume，指明一个数据存放的地址。这样，下次container被销毁时，重新生成的 postgres container，还可以读取前一个 container 的数据库数据
#### 什么是 docker | image | container
> Docker is a containerization platform that packages your application and all its dependencies together in the form of a docker container to ensure that your application works seamlessly in any environment.

#### Docker container 
你可以把 container 想像成一个小罐子，你的代码和环境被打包在这个小罐子里，不管代码跑在哪个环境里，都可以顺利运行  
#### Docker image      
而 Docker image 呢，就是制作小罐子的工具。image 和 container 的关系就像印刷板和印刷品，一个 image 可以生成好多个 container 供使用    
#### why Docker
用 Docker 呢，可以尽量避免开发环境写得爽，一放线上掉链子的情况，也可以让部署变得无痛一点          
另外，如果团队里有统一包好的 Docker image 了，新来的盆友可以直接用 Docker 把环境搭好，省去因为装不上开发环境而胸闷心悸的... grind
